### ISSUE TITLE
Stack deletion fails

### ISSUE THREAD

**Issue by laardee** [laardee/apig-usage-plan-cf#1]
Stack [apig-usage-plan.yml](https://github.com/laardee/apig-usage-plan-cf/blob/master/apig-usage-plan.yml) deletion fails
`11:50:14 UTC+0300	DELETE_FAILED	AWS::ApiGateway::UsagePlan	UsagePlan	Cannot delete Usage Plan wisqw9 because there are API Stages associated with it, including tkuwdfu7r2:dev`

The stack is successfully created, but the deletion fails because Stage is removed after UsagePlan.

The UsagePlan needs Stage to be created before itself

```yaml
  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
      - ApiId:
          Ref: ApiGateway
        Stage:
          Ref: ApiGatewayStage 
```

So I cannot add `DependsOn: ApiGatewayStage` to the UsagePlan.
